spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: seu-email
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
